### ISSUE TITLE
No Auto Brace Completion with ES6 IntelliSense

### ISSUE THREAD

**Issue by jackalsin** [Microsoft/nodejstools#1142]
First, thanks for your work
My question is how to make auto brace completion work.
Is that possible for you to review this [post](https://social.msdn.microsoft.com/Forums/en-US/a4fa3642-1d46-4027-a92f-a8247984ca3d/is-automatic-brace-completion-working-correctly-in-javascript?forum=vsx) ?

###copy from the post
is the Automatic Brace Completion really working?

It seems so according to the following youtube link:

                https://www.youtube.com/watch?v=ct4oW_cRMMw 

                at 02:10, and 

                https://www.youtube.com/watch?v=S5pXzp2PePw

                at 17:50

but I definitely check the box in Option->TextEditor->JavaScript->Automatic Brace Completion

I installed node js tool: NTVS.1.2.RC.VS.2015

Using VS 2015 Community under windows 10

Test this feature by creating an Express application and a blank javascript visual 

And I have reinstalled the VS already... and this feature in C++ and C# are working 

is there any trick I missed ? 

I really really really need this feature. This is the only flaw so far to develop a javascript program in VS

Please help
--------- end of the post --------------------

BTW, i notice Sara in the presentation video can do something like auto complete member in function like the video at 01:00 in the [link](https://channel9.msdn.com/events/Visual-Studio/Connect-event-2015/801)

**Comment by mjbvz** [comment]
Thanks for the report. I've confirmed this is an issue but it appears to be a Typescript problem: https://github.com/Microsoft/TypeScript/issues/1484 We use Typescript to power our modern IntelliSense experience and it looks like they will only start supporting automatic brace completion with Typescript 2.0.

I confirmed this is the root cause by switching from our Typescript powered editor/intellisense to our old static analysis engine powered ES5 intellisense: `Tools -> Options` then `Text Editor -> Node.js -> IntelliSense`. This restores automatic brace completion, however I strong recommend against doing this because there are a number of other benefits to the new Typescript IntelliSense experience.

**Comment by jackalsin** [comment]
May I ask how Sara did something like what she did in the video at 1:00 ?

**Comment by mjbvz** [comment]
The video was on an older version of NTVS so the behavior in 1.2 will be somewhat different. What specifically did you notice in the video? The part where it autocompletes the entire `function` instead of just the `function` keyword, or how she was able to fill in the function name?

**Comment by jackalsin** [comment]
Sorry. For English, I mean complete the entire function

**Comment by jackalsin** [comment]
Thank you,

Have a nice weekend~

**Comment by vBlueFlag** [comment]
I am waiting to fix this problem, too.

**Comment by mjbvz** [comment]
Typescript 2.0 should resolve this. Try [downloading the beta for VS2015]( https://github.com/Microsoft/TypeScript/releases) and checking the brace completion works as expected. You may have to manually enable the option back completion option again for Node.js to get it working.

**Comment by plushy1anthony999** [comment]
> You may have to manually enable the option back completion option again for Node.js to get it working.
Could you elaborate on what you mean here? Also, were you able to get brace completion after downloading the typescript 2.0 beta for VS2015? I've installed it, but still don't have brace completion.

**Comment by jackalsin** [comment]
Yeah. After this post, I tried the beta version, still not working.

**Comment by vBlueFlag** [comment]
So do I. I installed TypeScript 2.0 Beta, even Typings by NPM first && plugin second. But Anythings did not work. Is it possible to fix someday?

**Comment by mjbvz** [comment]
Yes, I didn't realize that for VS15, this change is in TS 2.0.1: https://github.com/Microsoft/TypeScript/issues/9634, not the 2.0 beta. I'm not sure when that will become publicly available but will follow up with the TS team to make sure this is being addressed as soon as possible.

**Comment by mjbvz** [comment]
Quick update: still working with the Typescript team to coordinate this feature in VS2015. There is unfortunately no easy to for you to try this out in VS2015 at the moment.

To get brace completion today, you can try [NTVS on the VS15 preview](https://github.com/Microsoft/nodejstools/releases/tag/v1.2.Dev-7.24.2016) which should have brace completion enabled.

**Comment by vBlueFlag** [comment]
I just moved to VS Code. It's super better than VS2015. Thank you.

**Comment by mjbvz** [comment]
This has been fixed by [TypeScript 2.0 RC](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/).

![autobrace](https://cloud.githubusercontent.com/assets/12821956/18329863/6fecd854-750a-11e6-81c1-a8ca6a148276.gif)


To enable automatic brace completion:

1. Install [TypeScript 2.0RC](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/) on VS 2015 Update 3 or higher.
2. Open VS and go to `Tools -> Options` and then `Text Editor -> Node.js -> General` and select `Automatic brace completion` (If this is still not working, try enabling the same option in `Text Editor -> Typescript -> General` as well)

Brace completion should now be enabled for `{`, `[`,  `(`, `"`, `'`, and `<` (that last one is kind of odd actually for non jsx files, I'll check with typescript to make sure it is intended.)

Please let me know if you cannot get this to work still or have any feedback or suggestions on the feature.

Thanks.

**Comment by jackalsin** [comment]
PLase don't close too fast. In my end, it's still not working 

I am pretty sure I installed update 3 and I can see my TypeScript -> General -> automatic brace competion is gray

**Comment by jackalsin** [comment]
God, how hard is it. Just a stack!

**Comment by mjbvz** [comment]
@jackalsin Did you install [TypeScript 2.0 RC](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/)? That's the fix that added support for brace completion. 

We made the decision not to implement this feature on the NTVS side but instead pick it up from TypeScript because we want a consistent experience when editing JS and TS files across Visual Studio. This is the same reason we dropped our old IntelliSense engine in favor one powered by TypeScript.
