### ISSUE TITLE
Cannot debug mocha tests in VS 2017

### ISSUE THREAD

**Issue by dnovvak** [Microsoft/nodejstools#1713]
Recently I've got new PC to work with clean Windows 10 installation. I installed VS 2017 with Node.js and Python workloads only. In that configuration I cannot start debugger for mocha tests. Debugger works fine if launched in standard mode (F5).

##### Expected Behavior 
Debug mode should work for mocha tests too.

##### Actual Behavior 
Debugger does not start when trying to debug mocha test.

output:
```
[10/2/2017 10:45:36 AM Informational] ========== Discover test finished: 5 found (0:00:01.0859653) ==========
[10/2/2017 11:02:06 AM Informational] ------ Run test started ------
[10/2/2017 11:02:08 AM Error] An exception occurred while invoking executor 'executor://nodejstestexecutor/v1': Could not load file or assembly 'Microsoft.VisualStudio.OLE.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
[10/2/2017 11:02:08 AM Informational] ========== Run test finished: 0 run (0:00:02.034671) ==========
```

- NTVS Version: 1.0.0.0 (About Microsoft Visual Studio window), 1.4.10602.1 (Extensions and Updates window) - version mismatch is confusing a bit
- Visual Studio Version: 15.3.5 (Enterprise 2017)
- Node.js Version: 6.11.3

##### Steps to Reproduce
1. Navigate to Test Explorer
2. Select any mocha test and from context menu choose: "Debug Selected Tests"

**Comment by paulvanbrenk** [comment]
Thanks this should be fixed in Visual Studio 2017 Update 4, which is due out this week. (Hopefully).

**Comment by ezequias** [comment]
@paulvanbrenk I am using VS Community 2017 15.5.2 and my mocha testes aren't still not showing in the Test Explorer.
Have you any idea why?

**Comment by paulvanbrenk** [comment]
Did you add the mocha tests using the Item Template from the "add new item" menu? And can you share your project file, and `package.json`

**Comment by ezequias** [comment]
@paulvanbrenk I haven't this option on my installation VS2017 Community. Could you tell me how to enable this template?
![image](https://user-images.githubusercontent.com/539561/34411749-00685d9a-ebc0-11e7-8b28-9784cc2d0ea3.png)

**Comment by paulvanbrenk** [comment]
Those are the project templates, I was looking for the item templates, on the project node, add new item.

![image](https://user-images.githubusercontent.com/5273975/34420588-4990ad84-ebbf-11e7-8fcd-9010a9e1837e.png)

Or you can change the test framework in the properties of a .js file:

![image](https://user-images.githubusercontent.com/5273975/34420623-72933eea-ebbf-11e7-9c1a-dd00f6fa82f2.png)

**Comment by ezequias** [comment]
Thanks @paulvanbrenk but I didn't have this templates.  Maybe I should download it from the store. I also added mocha to TestFrmework but it does not make the test appear into the Test Explorer. My new try is using VS Community 2015. Wish me luck,
