### ISSUE TITLE
Debugger Doesn't Work 75% Of The Time

### ISSUE THREAD

**Issue by atom0s** [Microsoft/nodejstools#246]
- Visual Studio 2013 (Update 4)
 - NTVS.Dev.2015-06-14.VS.2013.msi
 - Node v0.12.5

Most of the time, it seems that the debugger refuses to work properly. If I launch my application through Visual Studio, I would say about 75% of the time, it will show the debugger port in the console being 5858 and then nothing else happens. Typically if this occurs it requires me to restart Visual Studio entirely to get it to work again. And that point, it usually only works once, then dies again from there on til the next restart.

This issue happens with both the default startup path being set to the default:
C:\Program Files\nodejs\node.exe

As well as being set to something custom, such as nodemon:
C:\Users\atom0s\AppData\Roaming\npm\nodemon.cmd

Either or has the same issue.

**Comment by alejandro5042** [comment]
This may be related to this issue I reported yesterday #245. Can you confirm?

**Comment by atom0s** [comment]
Hello @alejandro5042 currently I am not using io.js, just using normal node with some packages such as:
 - express
 - passport
 - sequelize
 - vash

All of which I am pretty sure are the 32bit versions. Given that the debugging works sometimes but not always, I don't think that it is an issue with the version types though.

**Comment by mousetraps** [comment]
Haven't gotten the chance to look into it, but this sounds like a race condition, and we can't rule out the possibility it's related to #245 just yet... It could be that the recent x64 versions of iojs happen to exacerbate it.

**Comment by atom0s** [comment]
Thanks for the response @mousetraps - just to mention it again, I do not use io.js in my scenario. But I do seem to have a similar issue to what alejandro5042 is mentioning in his ticket.

**Comment by alejandro5042** [comment]
Actually, you bring up a good point with the race condition. Even with the io.js x86 which actually works vs. x64, I still have an issue with setting breakpoints. I cannot seem to hit a breakpoint in the first couple of lines of code, yet I can set and hit breakpoints in callbacks that occur after. I just did a little testing and observed that any breakpoint in the first 2 seconds of execution are not hit... anything after works. Thanks for attempting to investigate this @mousetraps!

**Comment by ant-fx** [comment]
I have a similar issue but not so frequent, maybe 50% of the time. I get a message saying debugger listening on port 5858 and then nothing.

I've tried uninstalling 64 bit and installing 32 bit but the problem is still there.

I don't need to restart Visual Studio, I just have to stop and start the app until the debugger kicks in. After a while it gets quite bad and restarting VS does help.

Running:

VS 2015 RC
Node: v0.12.6 (x32 + x64)
NTVS: 1.1 beta

**Comment by ant-fx** [comment]
After about an hour or so of testing with the x32 version, it does still happen but no where near as often as with the x64 version.

**Comment by mousetraps** [comment]
@ant-fx just realized you're on 1.1 beta - you should try one of our latest dev builds if we haven't already, as we fixed a race condition that solved similar issues 
https://github.com/Microsoft/nodejstools/releases

@atom0s unfortunately I can't repro this one yet, but maybe implementing #271 will help us get to the bottom of it. In the meantime, if you want to dig into this yourself, it would be helpful if you could run NTVS under the debugger and send us the log printed to the output window.

**Comment by nrossol** [comment]
I have the exact same issue, produced like this:

1: Create an express 3 application from the built-in template.
2: Press Debug button (with Google Chrome, for example)

Result:
90% of the time for me, I only get the console window displaying the message: "Debugger listening on port 5858". The Output panel is blank for everything (Debug, Build, General). The node server is not running, the web browser does not launch. I have waited for up to 10 minutes, and there is no change from this state.

Possible Work-around:
Occasionally, hitting the "Break All (Ctrl+Alt+Break)" button will cause the yellow debug cursor to appear on the very first line of "app.js". If this happens, pressing the "Continue" button sometimes causes everything to work as expected there-after (node server launches, browser pops up, everything works, including interactive debugging).

Unfortunately, sometimes pressing the "break-all" button does not cause the yellow debug cursor to appear on the first line of app.js, and pressing "Continue" does not help at all (still stuck in the same state). Sometimes pressing the "break-all" button causes visual studio to completely freeze until you force-quit the running node.exe process.

The seemingly random nature of all these issues really does seem to suggest some kind of race-condition is at play.

**Comment by mousetraps** [comment]
@nrossol since you just joined us... have you tried the latest dev build? We fixed a similar race condition there, and I can't tell you whether it's the same one you're running into but you should definitely upgrade if you weren't already on the 06-15-2015 build. 
https://github.com/Microsoft/nodejstools/releases

**Comment by nrossol** [comment]
Hi! The build I used and encountered this bug in is NTVS.Dev.2015-07-15.VS.2013 (I just updated/installed it earlier today).

**Comment by atom0s** [comment]
Sorry for the delayed response. This issue happens for me with express 3 as well mainly.

@mousetraps Is there a certain way you would like me to dig into things to try and collect information for you to better find the cause of this issue?

**Comment by mousetraps** [comment]
@atom0s We already have debugger logging when you're running NTVS with the debug bits and the debugger attached, and the most helpful thing to do would be to just send us the output from the output window from one run where debugging isn't working (and one where it is, if possible.) 

Then we can do a diff on those two runs, which will help us narrow down where a race condition might be coming from. 

As stated in #271, in the future we plan to surface up that information via an optional logging flag so that it's easier to diagnose problems like this that we can't reproduce.

**Comment by atom0s** [comment]
I have update to Visual Studio 2015 RTM and installed the new NTVS 1.1 package from here:
http://aka.ms/ntvs1.1rc2015
*(I'm not using the first link, but the 2nd one in the release since I'm not using the community version of 2015.)*

While debugging my teams API project, everything works great. however our front end project that makes use of express 3 is when the issues start happening again. It seems that NTVS and express 3 have issues working well together.

Also I am unsure if I am missing something but I get literally nothing in the output window when it does and doesn't work. Such as right now testing things for this post, debugging is working. Yet the output window is completely empty. (Assuming you are referring to Visual Studio's output window.) See here: http://i.imgur.com/p9dQWjG.png

From the past tests, when debugging is not working properly, the output window was also empty.

**Comment by mousetraps** [comment]
I wasn't entirely clear, I meant you would need to download the NTVS src and attach a debugger while you're debugging in order to see this output :smiley: In any case, #271 is now available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases), which means that you can turn on Live Debugging from **Tools** > **Node.js Tools** > **Diagnostic Info...**, and check the **Enable Node.js Tools Live Diagnostics output pane** box

![image](https://cloud.githubusercontent.com/assets/762848/9069314/685274da-3a9d-11e5-9c9b-4f539c7a6690.png)

Then, during your debug sessions, output will be available in the **Node.js Tools Live Diagnostics** output pane

![image](https://cloud.githubusercontent.com/assets/762848/9069425/01571078-3a9e-11e5-9224-1d8b95016ecf.png)

So when you run into an issue, you can just copy and paste the last debug session output into a window (each debug session begins with a bunch of `------`s.

For instance, this is the sort of output we are expecting to see from Node v0.12.4 running a ```console.log('hello world')``` and exiting the process by closing the console window that pops up. 
https://gist.github.com/mousetraps/bd5662028d9190f095cc

In your case, it would be helpful to grab the output after you launch debugging and see nothing happening.

**Comment by noopole** [comment]
I've got the exact same issue, even with a one-line console nodejs project, and the last NTVS build.

However adding `debugger` at the first line of the javascript file definitely eliminated the problem (for me)

**Comment by kant2002** [comment]
I have debugger not attached, and restart debugger. Issue reappear again:
Below the output of the issue:
```
[10:36:10.4256625] AD7Engine Called Terminate
[10:36:10.4346676] AD7Engine Called CanTerminateProcess
[10:36:10.4346676] AD7Engine Called TerminateProcess
[10:36:10.4376674] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ProgramDestroyEvent (E147E9E3-6440-4073-A7B7-A65592C714B5)
[10:36:10.4396722] AD7Engine Called ContinueFromSynchronousEvent
[10:36:10.4356699] DebuggerConnection: Connection was closed.
[10:36:23.5323318] --------------------------------------------------------------------------------
[10:36:23.5323318] AD7Engine Created (58459708)
[10:36:23.5333328] AD7Engine Called SetRegistryRoot
[10:36:23.5333328] AD7Engine Called SetLocale
[10:36:23.5353342] AD7Engine LaunchSuspended Called with flags 'LAUNCH_ENABLE_ENC' (58459708)
[10:36:23.6844315] Debugger connecting to URI: tcp://localhost:5858/
[10:36:24.1867630] Debugger connected successfully
[10:36:24.1867630] DebuggerConnection: Request: {"command":"scripts","seq":1,"type":"request","arguments":{"includeSource":false}}
[10:36:24.1877628] AD7Engine Finalized (54065174)
[10:36:24.1867630] DebuggerConnection: Established connection.
[10:36:24.2367961] DebuggerConnection: Response: {"seq":0,"request_seq":1,"type":"response","command":"scripts","success":true,"body":[{"handle":1,"type":"script","name":"_stream_transform.js","id":67,"lineOffset":0,"columnOffset":0,"lineCount":206,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":7312,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"_stream_transform.js (lines: 206)"},{"handle":3,"type":"script","name":"util.js","id":56,"lineOffset":0,"columnOffset":0,"lineCount":753,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":20149,"scriptType":2,"compilationType":0,"context":{"ref":2},"text":"util.js (lines: 753)"},{"handle":5,"type":"script","name":"_linklist.js","id":71,"lineOffset":0,"columnOffset":0,"lineCount":78,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":2217,"scriptType":2,"compilationType":0,"context":{"ref":4},"text":"_linklist.js (lines: 78)"},{"handle":7,"type":"script","name":"smalloc.js","id":69,"lineOffset":0,"columnOffset":0,"lineCount":97,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":3509,"scriptType":2,"compilationType":0,"context":{"ref":6},"text":"smalloc.js (lines: 97)"},{"handle":9,"type":"script","name":"fs.js","id":62,"lineOffset":0,"columnOffset":0,"lineCount":1884,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":48125,"scriptType":2,"compilationType":0,"context":{"ref":8},"text":"fs.js (lines: 1884)"},{"handle":11,"type":"script","name":"_stream_passthrough.js","id":68,"lineOffset":0,"columnOffset":0,"lineCount":43,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":1707,"scriptType":2,"compilationType":0,"context":{"ref":10},"text":"_stream_passthrough.js (lines: 43)"},{"handle":13,"type":"script","name":"buffer.js","id":57,"lineOffset":0,"columnOffset":0,"lineCount":965,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":24164,"scriptType":2,"compilationType":0,"context":{"ref":12},"text":"buffer.js (lines: 965)"},{"handle":15,"type":"script","name":"events.js","id":55,"lineOffset":0,"columnOffset":0,"lineCount":319,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":8987,"scriptType":2,"compilationType":0,"context":{"ref":14},"text":"events.js (lines: 319)"},{"handle":17,"type":"script","name":"node.js","id":54,"lineOffset":0,"columnOffset":0,"lineCount":815,"sourceStart":"// Copyright Joyent, Inc. and other Node contributors.\n//\n// Permission is hereb","sourceLength":23833,"scriptType":2,"compilationType":0,"context":{"ref":16},"text":"node.js (lines: 815)"},{"handle":19,"type":"script","name":"assert.js","id":61,"lineOffset":0,"columnOffset":0,"lineCount":317,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // http://wiki.com","sourceLength":10653,"scriptType":2,"compilationType":0,"context":{"ref":18},"text":"assert.js (lines: 317)"},{"handle":21,"type":"script","name":"stream.js","id":63,"lineOffset":0,"columnOffset":0,"lineCount":129,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":3630,"scriptType":2,"compilationType":0,"context":{"ref":20},"text":"stream.js (lines: 129)"},{"handle":23,"type":"script","name":"_stream_readable.js","id":64,"lineOffset":0,"columnOffset":0,"lineCount":914,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":25511,"scriptType":2,"compilationType":0,"context":{"ref":22},"text":"_stream_readable.js (lines: 914)"},{"handle":25,"type":"script","name":"vm.js","id":60,"lineOffset":0,"columnOffset":0,"lineCount":79,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":2844,"scriptType":2,"compilationType":0,"context":{"ref":24},"text":"vm.js (lines: 79)"},{"handle":27,"type":"script","name":"_stream_duplex.js","id":66,"lineOffset":0,"columnOffset":0,"lineCount":73,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":2577,"scriptType":2,"compilationType":0,"context":{"ref":26},"text":"_stream_duplex.js (lines: 73)"},{"handle":29,"type":"script","name":"path.js","id":58,"lineOffset":0,"columnOffset":0,"lineCount":628,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":16483,"scriptType":2,"compilationType":0,"context":{"ref":28},"text":"path.js (lines: 628)"},{"handle":31,"type":"script","name":"timers.js","id":70,"lineOffset":0,"columnOffset":0,"lineCount":591,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15200,"scriptType":2,"compilationType":0,"context":{"ref":30},"text":"timers.js (lines: 591)"},{"handle":33,"type":"script","name":"module.js","id":59,"lineOffset":0,"columnOffset":0,"lineCount":543,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15182,"scriptType":2,"compilationType":0,"context":{"ref":32},"text":"module.js (lines: 543)"},{"handle":35,"type":"script","name":"_stream_writable.js","id":65,"lineOffset":0,"columnOffset":0,"lineCount":503,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":14040,"scriptType":2,"compilationType":0,"context":{"ref":34},"text":"_stream_writable.js (lines: 503)"}],"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"},{"handle":2,"type":"context","text":"#<ContextMirror>"},{"handle":4,"type":"context","text":"#<ContextMirror>"},{"handle":6,"type":"context","text":"#<ContextMirror>"},{"handle":8,"type":"context","text":"#<ContextMirror>"},{"handle":10,"type":"context","text":"#<ContextMirror>"},{"handle":12,"type":"context","text":"#<ContextMirror>"},{"handle":14,"type":"context","text":"#<ContextMirror>"},{"handle":16,"type":"context","text":"#<ContextMirror>"},{"handle":18,"type":"context","text":"#<ContextMirror>"},{"handle":20,"type":"context","text":"#<ContextMirror>"},{"handle":22,"type":"context","text":"#<ContextMirror>"},{"handle":24,"type":"context","text":"#<ContextMirror>"},{"handle":26,"type":"context","text":"#<ContextMirror>"},{"handle":28,"type":"context","text":"#<ContextMirror>"},{"handle":30,"type":"context","text":"#<ContextMirror>"},{"handle":32,"type":"context","text":"#<ContextMirror>"},{"handle":34,"type":"context","text":"#<ContextMirror>"}],"running":true}
[10:36:24.2407983] DebuggerConnection: Request: {"command":"backtrace","seq":2,"type":"request","arguments":{"fromFrame":0,"toFrame":2147483647,"inlineRefs":true}}
[10:36:24.2658148] DebuggerConnection: Response: {"seq":1,"request_seq":2,"type":"response","command":"backtrace","success":true,"body":{"fromFrame":0,"toFrame":5,"totalFrames":5,"frames":[{"type":"frame","index":0,"receiver":{"ref":0,"type":"object","className":"Object"},"func":{"ref":1,"type":"function","name":"","inferredName":"win32.extname","scriptId":58},"script":{"ref":3},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"path","value":{"ref":4,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}}],"locals":[],"position":10365,"line":358,"column":24,"sourceLineText":"win32.extname = function(path) {","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#00 #<Object>.extname(path=E:\\d\\kant\\sytex\\metrix-web\\bin\\www) path.js line 359 column 25 (position 10366)"},{"type":"frame","index":1,"receiver":{"ref":8,"type":"object","className":"Object"},"func":{"ref":9,"type":"function","name":"","inferredName":"Module.load","scriptId":59},"script":{"ref":11},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"filename","value":{"ref":4,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}}],"locals":[{"name":"extension","value":{"ref":6,"type":"undefined"}}],"position":10097,"line":352,"column":23,"sourceLineText":"  var extension = path.extname(filename) || '.js';","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#01 #<Module>.load(filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www) module.js line 353 column 24 (position 10098)"},{"type":"frame","index":2,"receiver":{"ref":12,"type":"function","name":"Module","inferredName":"","scriptId":59},"func":{"ref":14,"type":"function","name":"","inferredName":"Module._load","scriptId":59},"script":{"ref":11},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"request","value":{"ref":4,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}},{"name":"parent","value":{"ref":15,"type":"null","value":null}},{"name":"isMain","value":{"ref":16,"type":"boolean","value":true}}],"locals":[{"name":"filename","value":{"ref":4,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}},{"name":"cachedModule","value":{"ref":6,"type":"undefined"}},{"name":"replModule","value":{"ref":6,"type":"undefined"}},{"name":"module","value":{"ref":8,"type":"object","className":"Object"}},{"name":"hadException","value":{"ref":16,"type":"boolean","value":true}}],"position":8983,"line":309,"column":11,"sourceLineText":"    module.load(filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#02 function Module(id, parent) {\n  this.id = id;\n  this.exports = {};\n  this.parent = parent;\n  if (parent && parent.children) {\n    parent.children.push(this);\n  }\n\n  this.filename = null;\n  this.loaded = false;\n  this.children = [];\n}._load(request=E:\\d\\kant\\sytex\\metrix-web\\bin\\www, parent=null, isMain=true) module.js line 310 column 12 (position 8984)"},{"type":"frame","index":3,"receiver":{"ref":18,"type":"object","className":"Object"},"func":{"ref":19,"type":"function","name":"","inferredName":"Module.runMain","scriptId":59},"script":{"ref":11},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[],"position":14219,"line":500,"column":9,"sourceLineText":"  Module._load(process.argv[1], null, true);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#03 #<Object>._onTimeout() module.js line 501 column 10 (position 14220)"},{"type":"frame","index":4,"receiver":{"ref":22,"type":"object","className":"Timer"},"func":{"ref":23,"type":"function","name":"listOnTimeout","inferredName":"","scriptId":70},"script":{"ref":25},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[{"name":"msecs","value":{"ref":26,"type":"number","value":50}},{"name":"now","value":{"ref":27,"type":"number","value":324967652}},{"name":"diff","value":{"ref":28,"type":"number","value":59}},{"name":"first","value":{"ref":18,"type":"object","className":"Object"}},{"name":"threw","value":{"ref":16,"type":"boolean","value":true}},{"name":"domain","value":{"ref":6,"type":"undefined"}},{"name":"oldDomain","value":{"ref":6,"type":"undefined"}},{"name":"list","value":{"ref":22,"type":"object","className":"Timer"}}],"position":3787,"line":118,"column":14,"sourceLineText":"        first._onTimeout();","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#04 #<Timer>[0](aka listOnTimeout)() timers.js line 119 column 15 (position 3788)"}]},"refs":[{"handle":3,"type":"script","name":"path.js","id":58,"lineOffset":0,"columnOffset":0,"lineCount":628,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":16483,"scriptType":2,"compilationType":0,"context":{"ref":2},"text":"path.js (lines: 628)"},{"handle":11,"type":"script","name":"module.js","id":59,"lineOffset":0,"columnOffset":0,"lineCount":543,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15182,"scriptType":2,"compilationType":0,"context":{"ref":10},"text":"module.js (lines: 543)"},{"handle":25,"type":"script","name":"timers.js","id":70,"lineOffset":0,"columnOffset":0,"lineCount":591,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15200,"scriptType":2,"compilationType":0,"context":{"ref":24},"text":"timers.js (lines: 591)"}],"running":true}
[10:36:24.2738231] Thread created: 1
[10:36:24.2748234] AD7Engine LaunchSuspended returning S_OK
[10:36:24.2748234] DebuggerConnection: Response: {"seq":2,"type":"event","event":"compileError","success":true,"body":{"script":{"handle":1,"type":"script","name":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www","id":72,"lineOffset":0,"columnOffset":0,"lineCount":35,"sourceStart":"(function (exports, require, module, __filename, __dirname) { \r\n\r\nvar path = req","sourceLength":1023,"scriptType":2,"compilationType":0,"context":{"ref":0},"text":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www (lines: 35)"}},"refs":[{"handle":0,"type":"context","text":"#<ContextMirror>"}],"running":true}
[10:36:24.3028389] DebuggerConnection: Response: {"seq":3,"type":"event","event":"break","body":{"invocationText":"#<Object>.[anonymous](exports=#<Object>, require=function require(path) {\n    return self.require(path);\n  }, module=#<Module>, __filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www, __dirname=E:\\d\\kant\\sytex\\metrix-web\\bin)","sourceLine":2,"sourceColumn":0,"sourceLineText":"var path = require(\"path\"),","script":{"id":72,"name":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www","lineOffset":0,"columnOffset":0,"lineCount":35},"breakpoints":[1]}}
[10:36:24.9982986] DebuggerConnection: Request: {"command":"backtrace","seq":3,"type":"request","arguments":{"fromFrame":0,"toFrame":2147483647,"inlineRefs":true}}
[10:36:25.0543373] AD7Engine Called ResumeProcess
[10:36:25.0553384] AD7Engine Called Attach
[10:36:25.0553384] Sending load complete (58459708)
[10:36:25.0553384] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7EngineCreateEvent (FE5B734C-759D-4E59-AB04-F103343BDD06)
[10:36:25.0553384] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ProgramCreateEvent (96CD11EE-ECD4-4E89-957E-B5D496FC4139)
[10:36:25.0553384] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0563387] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0573402] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0573402] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0573402] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0573402] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0573402] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0583404] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0583404] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0583404] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0583404] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0583404] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0593389] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
[10:36:25.0593389] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ThreadCreateEvent (2090CCFC-70C5-491D-A5E8-BAD2DD9EE3EA)
[10:36:25.0593389] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7LoadCompleteRunningEvent (B1844850-1349-45D4-9F12-495212F5EB0B)
[10:36:25.0593389] AD7Engine Attach returning S_OK
[10:36:25.0093063] DebuggerConnection: Response: {"seq":4,"request_seq":3,"type":"response","command":"backtrace","success":true,"body":{"fromFrame":0,"toFrame":7,"totalFrames":7,"frames":[{"type":"frame","index":0,"receiver":{"ref":1,"type":"object","className":"Object"},"func":{"ref":0,"type":"function","name":"","inferredName":"","scriptId":72},"script":{"ref":12},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"exports","value":{"ref":1,"type":"object","className":"Object"}},{"name":"require","value":{"ref":6,"type":"function","name":"require","inferredName":"","scriptId":59}},{"name":"module","value":{"ref":7,"type":"object","className":"Object"}},{"name":"__filename","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}},{"name":"__dirname","value":{"ref":10,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin"}}],"locals":[{"name":"path","value":{"ref":3,"type":"undefined"}},{"name":"app","value":{"ref":3,"type":"undefined"}},{"name":"AppIo","value":{"ref":3,"type":"undefined"}},{"name":"server","value":{"ref":3,"type":"undefined"}},{"name":"port","value":{"ref":3,"type":"undefined"}}],"position":66,"line":2,"column":0,"sourceLineText":"var path = require(\"path\"),","scopes":[{"type":1,"index":0},{"type":0,"index":1}],"text":"#00 #<Object>.[anonymous](exports=#<Object>, require=function require(path) {\n    return self.require(path);\n  }, module=#<Module>, __filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www, __dirname=E:\\d\\kant\\sytex\\metrix-web\\bin) E:\\d\\kant\\sytex\\metrix-web\\bin\\www line 3 column 1 (position 67)"},{"type":"frame","index":1,"receiver":{"ref":7,"type":"object","className":"Object"},"func":{"ref":15,"type":"function","name":"","inferredName":"Module._compile","scriptId":59},"script":{"ref":14},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"content","value":{"ref":16,"type":"string","value":"\r\n\r\nvar path = require(\"path\"),\r\n    app = require(path.join(__dirname, \"../app\"... (length: 957)"}},{"name":"filename","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}}],"locals":[{"name":"require","value":{"ref":6,"type":"function","name":"require","inferredName":"","scriptId":59}},{"name":"dirname","value":{"ref":10,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin"}},{"name":"sandbox","value":{"ref":3,"type":"undefined"}},{"name":"k","value":{"ref":3,"type":"undefined"}},{"name":"wrapper","value":{"ref":17,"type":"string","value":"(function (exports, require, module, __filename, __dirname) { \r\n\r\nvar path = req... (length: 1023)"}},{"name":"compiledWrapper","value":{"ref":0,"type":"function","name":"","inferredName":"","scriptId":72}},{"name":"args","value":{"ref":18,"type":"object","className":"Array"}},{"name":"self","value":{"ref":7,"type":"object","className":"Object"}}],"position":13201,"line":459,"column":25,"sourceLineText":"  return compiledWrapper.apply(self.exports, args);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#01 #<Module>._compile(content=\r\n\r\nvar path = require(\"path\"),\r\n    app = require(path.join(__dirname, \"../app\"... (length: 957), filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www) module.js line 460 column 26 (position 13202)"},{"type":"frame","index":2,"receiver":{"ref":20,"type":"object","className":"Object"},"func":{"ref":21,"type":"function","name":"","inferredName":"Module._extensions..js","scriptId":59},"script":{"ref":14},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"module","value":{"ref":7,"type":"object","className":"Object"}},{"name":"filename","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}}],"locals":[{"name":"content","value":{"ref":22,"type":"string","value":"#!/usr/bin/env node\r\n\r\nvar path = require(\"path\"),\r\n    app = require(path.join(... (length: 976)"}}],"position":13688,"line":477,"column":9,"sourceLineText":"  module._compile(stripBOM(content), filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#02 #<Object>..js(module=#<Module>, filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www) module.js line 478 column 10 (position 13689)"},{"type":"frame","index":3,"receiver":{"ref":7,"type":"object","className":"Object"},"func":{"ref":23,"type":"function","name":"","inferredName":"Module.load","scriptId":59},"script":{"ref":14},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"filename","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}}],"locals":[{"name":"extension","value":{"ref":24,"type":"string","value":".js"}}],"position":10213,"line":354,"column":31,"sourceLineText":"  Module._extensions[extension](this, filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#03 #<Module>.load(filename=E:\\d\\kant\\sytex\\metrix-web\\bin\\www) module.js line 355 column 32 (position 10214)"},{"type":"frame","index":4,"receiver":{"ref":8,"type":"function","name":"Module","inferredName":"","scriptId":59},"func":{"ref":25,"type":"function","name":"","inferredName":"Module._load","scriptId":59},"script":{"ref":14},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[{"name":"request","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}},{"name":"parent","value":{"ref":5,"type":"null","value":null}},{"name":"isMain","value":{"ref":26,"type":"boolean","value":true}}],"locals":[{"name":"filename","value":{"ref":9,"type":"string","value":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www"}},{"name":"cachedModule","value":{"ref":3,"type":"undefined"}},{"name":"replModule","value":{"ref":3,"type":"undefined"}},{"name":"module","value":{"ref":7,"type":"object","className":"Object"}},{"name":"hadException","value":{"ref":26,"type":"boolean","value":true}}],"position":8983,"line":309,"column":11,"sourceLineText":"    module.load(filename);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#04 function Module(id, parent) {\n  this.id = id;\n  this.exports = {};\n  this.parent = parent;\n  if (parent && parent.children) {\n    parent.children.push(this);\n  }\n\n  this.filename = null;\n  this.loaded = false;\n  this.children = [];\n}._load(request=E:\\d\\kant\\sytex\\metrix-web\\bin\\www, parent=null, isMain=true) module.js line 310 column 12 (position 8984)"},{"type":"frame","index":5,"receiver":{"ref":28,"type":"object","className":"Object"},"func":{"ref":29,"type":"function","name":"","inferredName":"Module.runMain","scriptId":59},"script":{"ref":14},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[],"position":14219,"line":500,"column":9,"sourceLineText":"  Module._load(process.argv[1], null, true);","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#05 #<Object>._onTimeout() module.js line 501 column 10 (position 14220)"},{"type":"frame","index":6,"receiver":{"ref":32,"type":"object","className":"Timer"},"func":{"ref":33,"type":"function","name":"listOnTimeout","inferredName":"","scriptId":70},"script":{"ref":35},"constructCall":false,"atReturn":false,"debuggerFrame":false,"arguments":[],"locals":[{"name":"msecs","value":{"ref":36,"type":"number","value":50}},{"name":"now","value":{"ref":37,"type":"number","value":324967652}},{"name":"diff","value":{"ref":38,"type":"number","value":59}},{"name":"first","value":{"ref":28,"type":"object","className":"Object"}},{"name":"threw","value":{"ref":26,"type":"boolean","value":true}},{"name":"domain","value":{"ref":3,"type":"undefined"}},{"name":"oldDomain","value":{"ref":3,"type":"undefined"}},{"name":"list","value":{"ref":32,"type":"object","className":"Timer"}}],"position":3787,"line":118,"column":14,"sourceLineText":"        first._onTimeout();","scopes":[{"type":1,"index":0},{"type":3,"index":1},{"type":0,"index":2}],"text":"#06 #<Timer>[0](aka listOnTimeout)() timers.js line 119 column 15 (position 3788)"}]},"refs":[{"handle":12,"type":"script","name":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www","id":72,"lineOffset":0,"columnOffset":0,"lineCount":35,"sourceStart":"(function (exports, require, module, __filename, __dirname) { \r\n\r\nvar path = req","sourceLength":1023,"scriptType":2,"compilationType":0,"context":{"ref":11},"text":"E:\\d\\kant\\sytex\\metrix-web\\bin\\www (lines: 35)"},{"handle":14,"type":"script","name":"module.js","id":59,"lineOffset":0,"columnOffset":0,"lineCount":543,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15182,"scriptType":2,"compilationType":0,"context":{"ref":13},"text":"module.js (lines: 543)"},{"handle":35,"type":"script","name":"timers.js","id":70,"lineOffset":0,"columnOffset":0,"lineCount":591,"sourceStart":"(function (exports, require, module, __filename, __dirname) { // Copyright Joyen","sourceLength":15200,"scriptType":2,"compilationType":0,"context":{"ref":34},"text":"timers.js (lines: 591)"}],"running":false}
[10:36:25.0593389] ResumeProcess return S_OK
[10:36:25.0603396] AD7Engine Called GetEngineId
[10:36:25.0603396] AD7Engine Called SetMetric
[10:36:25.0603396] AD7Engine Called SetMetric
[10:36:25.0603396] AD7Engine Called SetMetric
[10:36:25.0603396] AD7Engine Called SetMetric
[10:36:25.0603396] AD7Engine Called SetMetric
[10:36:25.0603396] AD7Engine Called SetSymbolLoadState
[10:36:25.0603396] AD7Engine Called GetEngineId
[10:36:25.0603396] AD7Engine Called GetProgramId
[10:36:25.0613424] AD7Engine Called CanDetach
[10:36:25.0693486] AD7Engine Event: Microsoft.NodejsTools.Debugger.DebugEngine.AD7ModuleLoadEvent (989DB083-0D7C-40D1-A9D9-921BF611A4B2)
```

I would also suggest add more information about debugger event parameters. For example modules loaded, or function execution results.

**Comment by kant2002** [comment]
Actually maybe I experience different issue altogether, My Express application seems to be not started.
This is sporadic, as debugger issue described here, that's why I made mistake

**Comment by mousetraps** [comment]
Thx for all your patience with this issue. As I posted [here](https://github.com/microsoft/nodejstools/issues/362#issuecomment-139750182) I have a fix for this working locally on my machine if anyone feels like building locally and giving it a shot. No one on this thread has posted logs, but it certainly seems like the same issue based on the symptoms.

**Comment by mousetraps** [comment]
A fix for this issue is now available in our latest dev build. Check it out and let us know what you think! https://github.com/Microsoft/nodejstools/releases

cc/ @atom0s @alejandro5042 @ant-fx @nrossol

**Comment by atom0s** [comment]
Very sorry for my lack of replies here. I got side tracked with other projects and lost track of this ticket. I am installing the update now and will try and report back if I see any other problems. Thank you very much for staying on top of this bug and getting things worked out. :)

**Comment by purell** [comment]
Hi,

I was having the same problem, only working first time and I had to restart Visual Studio each time. But I have found what was causing my problem. I was using Navicat to edit my SQLite database and this one tend to use a kind of lock mechanism or transaction while it stay opened. In my code I was also starting transaction at server startup and this was the why it was hanging... I hope it may help somebody else with that problem :)

**Comment by purell** [comment]
mousetraps : I did wath you said about the "Diagnostic Info" windows and this is what I got when the debugger don't want to start : 

[20:48:26.2699168] --------------------------------------------------------------------------------
[20:48:26.2769168] AD7Engine Created (25640749)
[20:48:26.2769168] AD7Engine Called SetRegistryRoot
[20:48:26.2769168] AD7Engine Called SetLocale
[20:48:26.2769168] AD7Engine LaunchSuspended Called with flags 'LAUNCH_ENABLE_ENC' (25640749)
[20:48:27.0039168] AD7Engine Finalized (25640749)

It is helping you ?

**Comment by mjbvz** [comment]
Thank you for providing this info and sorry that you are running into problems.

@mousetraps, looking at the code, it seems we never hit this statement at the end of `IDebugEngineLaunch2.LaunchSuspended`:

```cs
 LiveLogger.WriteLine("AD7Engine LaunchSuspended returning S_OK");
```

I wonder if `NodeDebugger.StartListening` is timing out? That function throws an exception, which I believe would trigger this sequence of events (any other exception would do the same, but I see explicit `throw`s in that function).

**Comment by purell** [comment]
Is it anything new about this bug ?

**Comment by kant2002** [comment]
Maybe there need to reopen this issue? Or it is already fixed by @mjbvz

**Comment by purell** [comment]
I think the issue should be re-opened as I'm still having the same problem multiple time everyday. It's very annoying.

**Comment by mjbvz** [comment]
@kant2002 I have not done any work to address this problem but was hoping @mousetraps may have some extra context.

@purell Since this issue was originally scoped to a problem that has been resolved to my knowledge, please open a more targeted issue to track the specific problem you are running into. We want to fix this sort of problem, but I don't want to keep reanimating this thread.

(Also changing the name of this issue to clearly state that this issue was tracking a scoped problem, not general debugger failures)

**Comment by purell** [comment]
@mjbvz : Can I use the old title for the new post ? ie : "Debugger Doesn't Work 75% Of The Time". Or maybe "Debugger does not always start" ?

Because I don't know WHY the debugger is not starting and nor the percentage of failure but 75% is near the reality.

**Comment by mjbvz** [comment]
@purell If there are more specific situations when the debugger doesn't attach or other symptoms, try mentioning those, since it will make the issue more actionable. But if you are unsure what is going wrong, a generic title is a fine starting point.

The goal is to keep issues focused and make sure they track something we can actually resolve. 

Thanks.

**Comment by mousetraps** [comment]
@purell @mjbvz @kant2002 

Created a new issue here: https://github.com/Microsoft/nodejstools/issues/823

**Comment by purell** [comment]
@mousetraps thank you so much. I had had no time yesterday.
