### ISSUE TITLE
Invalid semantic version

### ISSUE THREAD

**Issue by emretto** [Microsoft/nodejstools#256]
Package list is downloaded properly. Then this "SemverVersionFormatException" occurs.

Things I already tried: Refreshing catalog and restarting VS 2013 as suggested, deleting "NpmCache" (for any case)...

Windows7 Professional
Visual Studio 2013 Community E.
Nodejs Tools v1.0

Registry url: https://registry.npmjs.org/
Path to npm: C:\Program Files\nodejs\npm.cmd
Downloading package cache to C:\Users\EmreO\AppData\Local\Microsoft\Node.js Tools\NpmCache\90443eff-25ed-4131-b318-59e310936f6e\all_packages.json
Downloading list of packages from https://registry.npmjs.org/-/all
Downloaded 1MB of the package list (92MB total)
Downloaded 2MB of the package list (92MB total)
...
Downloaded 90MB of the package list (92MB total)
Downloaded 91MB of the package list (92MB total)
Download complete - updating database
Reading 96019487 bytes from C:\Users\EmreO\AppData\Local\Microsoft\Node.js Tools\NpmCache\90443eff-25ed-4131-b318-59e310936f6e\all_packages.json (07.07.2015 11:00:32)
Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: '0.1.4-DEPRECATED-USE-cfenv-INSTEAD'. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-].
   at Microsoft.NodejsTools.Npm.SemverVersion.Parse(String versionString)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7.<ParseResultsAndAddToDatabase>b__1()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass3d.<ExecuteAsync>b__33()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__3f.MoveNext()
Download or parsing failed - deleting C:\Users\EmreO\AppData\Local\Microsoft\Node.js Tools\NpmCache. Try refreshing the catalog again. Otherwise restart Visual Studio, and try again.
Deleting 90443eff-25ed-4131-b318-59e310936f6e
Microsoft.NodejsTools.Npm.SemverVersionFormatException: Invalid semantic version: '0.1.4-DEPRECATED-USE-cfenv-INSTEAD'. The version number must consist of three non-negative numeric parts of the form MAJOR.MINOR.PATCH, with optional pre-release and/or build metadata. The optional parts may only contain characters in the set [0-9A-Za-z-].
   at Microsoft.NodejsTools.Npm.SemverVersion.Parse(String versionString)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass7.<ParseResultsAndAddToDatabase>b__1()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.ParseResultsAndAddToDatabase(TextReader reader, String dbFilename, String registryUrl)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<>c__DisplayClass3d.<ExecuteAsync>b__33()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmGetCatalogCommand.<ExecuteAsync>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.NodejsTools.Npm.SPI.NpmCommander.<DoCommandExecute>d__0.MoveNext()

**Comment by kant2002** [comment]
In the last version of NodeJS tools this already fixed. You should try NTVS1.1 Beta, it is stable enough.

**Comment by kant2002** [comment]
Maybe this is related to #253

**Comment by emretto** [comment]
I uninstalled NTVS1.0 and installed NTVS1.1Beta. 
Unfortunately, same error  occurs ==> http://txs.io/Mv6b

I think the output might be similar to the issue you refer (#253). The only difference: On my output a package catalog database is not asked to be upgraded.

**Comment by emretto** [comment]
On #253 it was strange that @kant2002 and @billti could install but not the two turkish users. I suppose @fatihyucelsen is also turkish like me. This brought me to an idea, and all works fine now.

Here is what worked for me:

*) Open Control Panel > Region and Language
*) On the Formats tab, chose "English (United States)" - as my former setting was "Turkish (Turkey)"
*) Open VS and retry.
*) Voila!

After doing this, I switched my regional setting back to turkish and NTVS keeps working. My guess is, unless the whole 92MB database is not downloaded, this will go.

Keep the good work guys!

**Comment by fatihyucelsen** [comment]
Settings challenge of correct English. Thanks friends.

**Comment by mousetraps** [comment]
Fix available in the [latest dev build](https://github.com/Microsoft/nodejstools/releases)

**Comment by cpoyraz** [comment]
Unfortunately, that bug is still alive in latest@VS Nodejs Tools 2017

**Comment by billti** [comment]
We don't even use this component any more in the most recent VS 2017 releases (the SQLite store of the NPM database), so it must be a different issue. Could you please confirm what you are seeing exactly?
