### ISSUE TITLE
VS2015 with node.js v.4.2.1 will cause cpu 100% and produce a lot of node.exe process.

### ISSUE THREAD

**Issue by jimior2** [Microsoft/nodejstools#565]
When I turn VS2015 refer use node.js v4.2.1, this will cause cpu reach100% and produce a lot of node.exe process, but when i turn back to node.js v0.10.31 will be fine. did nodejstools didn't support v4.2.1 yet?

**Comment by mousetraps** [comment]
That's interesting. Haven't had any issues with node v4.2.1 myself.

Do you have resharper installed by any chance? Could you take a screenshot of the node processes in task manager when you turn the "command line arguments" column on?

**Comment by mousetraps** [comment]
Also are you doing anything specific when these processes spawn?

**Comment by jimior2** [comment]
Hi @mousetraps , when i use npm to install which is working well when using command line with node v4.2.1 to me. But the issue is when I use VS2015 with node v4.2.1 will cause this issue.
![image](https://cloud.githubusercontent.com/assets/654999/10720935/5aee971c-7bd7-11e5-8753-20bc1fe113cf.png)

I've try 2 kind of project so far as below:

The steps are:
1. Create a new project - TypeScript - HTML Application with TypeScript
2. Add New Item for "NPM configuration file" to project
3. And package to this file in "devDependencies" and save.
4. Then multiple node.exe produce and cpu high almost 100%
![image](https://cloud.githubusercontent.com/assets/654999/10720917/22e6107a-7bd7-11e5-9b54-0a8088bf79f8.png)


1. Creat a new project - ASP.NET Web Application - ASP.NET 5 Preview Templates(Empty)
2. Add New Item for "NPM configuration file" to project.
3. Then multiple node.exe produce and cpu high alost 100%
![image](https://cloud.githubusercontent.com/assets/654999/10720923/38879f5c-7bd7-11e5-872b-def444af796e.png)


When I turn back to use VS2015 default Web Tools node v0.10.31, then there's no problem for me.
![image](https://cloud.githubusercontent.com/assets/654999/10720983/fcc7b3ac-7bd7-11e5-860b-9d967474e817.png)

**Comment by billti** [comment]
Thanks @jimior2 . Are you using Node Tools for Visual Studio at all? In these scenarios (TypeScript HTML app or ASP.NET project) the NTVS tools don't get used, so it would appear to be a separate Visual Studio issue (I believe the Web Tools also kick off Node/NPM for certain functionality). We can try and investigate with the right team if this isn't an NTVS issue.

**Comment by mousetraps** [comment]
@jimior2 are you running McAfee or some other virus scanner by any chance? If so, could you try turning off scanning for the node_modules directory and see if that resolves the issue?

@billti the rest of Visual Studio currently relies on our component for any npm integration, so we would need to resolve it on our end. We've also had a few users run into this issue at some point - it's been around for a while - but we were never able to track it down :frowning:. Since then, our codebase has changed to execute `npm bin -g --silent` rather than `npm ls -g` (VS is currently shipping an older version of the npm component). In any case, at some point we thought we resolved the issue, but unfortunately that fix only worked for about 50% of the people running into it (that said, I have a feeling this fix never made its way into Web Tools, so it very well could be resolved in this specific instance). Here's the original thread, and I also did some investigation over email at some point. https://nodejstools.codeplex.com/workitem/1791

And here's a video that one of our users recorded of the issue one time: http://screencast.com/t/QiKfmB67w

One interesting note from the video is that the first process never dies. And notice that it is actually spawned differently than the second process. The long-lived process was actually spun off in a background thread, whereas the completing process was not.
* long-lived process: https://github.com/Microsoft/nodejstools/blob/8169f1e6fe7c83e3f4061631a44de79b3e80ec73/Nodejs/Product/Npm/SPI/NpmController.cs#L157
* recurring, but completing process: https://github.com/Microsoft/nodejstools/blob/8169f1e6fe7c83e3f4061631a44de79b3e80ec73/Nodejs/Product/Npm/SPI/NpmController.cs#L132

So one question is... why would this make any difference?

The other question is... how is it even possible to have more than two `npm bin -g` processes ever running at one time in a solution with a single project?

I also believe McAfee either causes or exacerbates the issue, and my hunch is that for some reason the modify some file property when they touch the file during on-access scanning, which causes our file watcher to trigger unnecessarily often, which causes the on-access scanner to trigger, ad infinitum. (one of our earlier user reported that there were 2 files on his system that seemed to be getting scanned consistently.)

**Comment by mousetraps** [comment]
@jimior2 does this issue occur for you with Node.js Tools when you create, say, a new Node.js Express project? https://github.com/Microsoft/nodejstools/issues/releases

Otherwise there's a good chance we've already fixed this in NTVS (and just need to pull those changes into VS).

**Comment by mousetraps** [comment]
We're swapping the npm component in VS with a new one in a future release. Closing as it's not NTVS-releated.

**Comment by Nikhil13x** [comment]
McAfee on access scan holds nodejs from accessing any file. Add exception for the source code folder in on access scan should solve this.

**Comment by zinduyaar** [comment]
Is this issue resolved?
I need some help, I am still getting the high CPU usage(100%) issue using Visual Studio 2015 with nodejs tools.
Below is my configuration:
node version: v4.4.6
Visual Studio 2015 Update 3 ASP.NET 5
Visual Studio is working fine untill I load any package from npm configuration file, after that this happens.
![lotsofnodeprocesses](https://cloud.githubusercontent.com/assets/4686791/17508837/a53e8936-5e34-11e6-9443-4d35858eb346.png)
